### PR TITLE
Jupyter Presentation

### PR DESCRIPTION
**Pull request by jeremylt**

### CODE REVIEW

**Comment by jedbrown** [comment]
These are the two extensions I use with RISE:
https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/splitcell/readme.html
https://github.com/kirbs-/hide_code

**Comment by jeremylt** [comment]
Do you have a trick to pin the title at the top of the page so it doesn't jump a little on each slide?

Really, I should peak at your class repo

**Comment by jedbrown** [comment]
I don't, but if there is a way, it'll probably be in reveal.js and/or CSS, not the Jupyter/RISE part.

**Comment by jeremylt** [comment]
I was afraid that'd probably be the case. I'll tinker (and probably consult @ArielLeslie)

**Comment by jeremylt** [comment]
Note to self: Merging intermediate work and some small bugfixes discovered - will pick up presentation again after QFunction update PR

**Pull request merged**
